"""Knowledge base, part A: apps 1-50 (Pass-1 priors).

'confidence' = how many independent signals backed the claim at write time
(docs page live, auth mentioned on page, registry listed, etc.).
1-2 => low (queued for the human/live pass), 3+ => solid.
"""
from config import AppRecord

R = AppRecord

APPS_A = [
    # ---------------- 1. CRM and Sales ----------------
    R(1, "Salesforce", "CRM and Sales", "Enterprise CRM platform (Sales Cloud)",
        "OAuth2", "Gated", "Full REST", "~700+ objects, huge", "Yes",
        "Ready", "Developer org signup is free but API access needs Enterprise/Unlimited edition",
        "https://developer.salesforce.com/docs/einstein/genai/references/rest-api", 3,
        "Free dev org exists; production API gated by edition."),
    R(2, "HubSpot", "CRM and Sales", "Inbound CRM + marketing suite",
        "OAuth2", "Self-serve", "Full REST", "200+ endpoints", "Yes",
        "Ready", "",
        "https://developers.hubspot.com/docs/api/overview", 3,
        "Free CRM tier includes private-app tokens; OAuth for multi-tenant."),
    R(3, "Pipedrive", "CRM and Sales", "Sales-focused CRM for SMBs",
        "API key", "Self-serve", "Full REST", "~100 endpoints", "Yes",
        "Ready", "",
        "https://developer.pipedrive.com/docs/api/v1", 3, ""),
    R(4, "Attio", "CRM and Sales", "Modern data-model-first CRM",
        "Bearer token", "Self-serve", "Full REST", "~90 endpoints", "Yes",
        "Ready", "",
        "https://docs.attio.com/rest-api/how-to/authentication", 3, ""),
    R(5, "Twenty", "CRM and Sales", "Open-source CRM (Salesforce alternative)",
        "Bearer token", "Open", "Full REST", "REST + GraphQL, ~80 endpoints", "Yes",
        "Ready", "",
        "https://docs.twenty.com/developer-docs/docs/rest-api/introduction", 3,
        "Open-source; self-host or Twenty cloud free tier."),
    R(6, "Podio", "CRM and Sales", "Customizable work management + CRM",
        "OAuth2", "Self-serve", "Full REST", "~200 endpoints", "No",
        "Ready with caveats", "Aging API; app-auth model adds friction",
        "https://developers.podio.com/authentication", 2,
        "Progress-owned; API stable but barely updated."),
    R(7, "Zoho CRM", "CRM and Sales", "SMB/enterprise CRM suite",
        "OAuth2", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "API quota depends on plan tier",
        "https://www.zoho.com/crm/developer/docs/api/v6/", 3, ""),
    R(8, "Close", "CRM and Sales", "Sales CRM for startups (email-calling native)",
        "API key", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "",
        "https://developer.close.com", 3, ""),
    R(9, "Copper", "CRM and Sales", "Google-Workspace-native CRM",
        "API key", "Self-serve", "Full REST", "~70 endpoints", "Yes",
        "Ready", "API needs paid plan (Professional+)",
        "https://developer.copper.com", 3, ""),
    R(10, "DealCloud", "CRM and Sales", "Financial-services CRM (Intapp)",
        "Basic", "Gated", "Full REST", "~100 endpoints", "No",
        "Blocked", "Vendor onboarding; API credentials provisioned by admin/Intapp",
        "https://api.docs.dealcloud.com", 2,
        "Docs are live (client-provided); signup is a sales process."),

    # ---------------- 2. Support and Helpdesk ----------------
    R(11, "Zendesk", "Support and Helpdesk", "Customer-support ticketing suite",
        "Bearer token", "Self-serve", "Full REST", "~300 endpoints", "Yes",
        "Ready", "API on all plans, trial available",
        "https://developer.zendesk.com/api-reference", 3, ""),
    R(12, "Intercom", "Support and Helpdesk", "Customer-messaging + support platform",
        "Bearer token", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "",
        "https://developers.intercom.com/docs/references/rest-api/api.intercom.io", 3, ""),
    R(13, "Freshdesk", "Support and Helpdesk", "Freshworks helpdesk",
        "API key", "Self-serve", "Full REST", "~120 endpoints", "Yes",
        "Ready", "Free trial; API on all paid plans",
        "https://developers.freshdesk.com/api", 3, ""),
    R(14, "Front", "Support and Helpdesk", "Shared-inbox customer-ops platform",
        "API key", "Self-serve", "Full REST", "~180 endpoints", "Yes",
        "Ready", "14-day trial then paid plan needed",
        "https://dev.frontapp.com", 3, ""),
    R(15, "Pylon", "Support and Helpdesk", "B2B support (Slack-first helpdesk)",
        "API key", "Gated", "Narrow REST", "~40 endpoints", "Yes",
        "Ready with caveats", "Product is sales-led; API docs public, keys via dashboard",
        "https://docs.usepylon.com/api-reference/authentication", 2, ""),
    R(16, "LiveAgent", "Support and Helpdesk", "Helpdesk + live chat",
        "API key", "Self-serve", "Narrow REST", "~60 endpoints", "No",
        "Ready with caveats", "API keys via agent dashboard; free plan lacks API",
        "https://liveagent.com/api", 2, ""),
    R(17, "Plain", "Support and Helpdesk", "API-first customer support for dev tools",
        "API key", "Self-serve", "GraphQL", "GraphQL schema, ~50 ops", "Yes",
        "Ready", "",
        "https://developers.plain.com", 3, "GraphQL-first; also JSON API for some resources."),
    R(18, "Help Scout", "Support and Helpdesk", "Shared inbox + help center",
        "API key", "Self-serve", "Full REST", "~70 endpoints", "No",
        "Ready", "",
        "https://developer.helpscout.com/mailbox-api", 3, ""),
    R(19, "Gorgias", "Support and Helpdesk", "Ecommerce helpdesk (Shopify-native)",
        "Bearer token", "Gated", "Narrow REST", "~50 endpoints", "Yes",
        "Ready with caveats", "Paid plans only; trial requires demo call",
        "https://developers.gorgias.com/reference", 2, ""),
    R(20, "Gladly", "Support and Helpdesk", "Customer-service platform (people-centric)",
        "Basic", "Gated", "Narrow REST", "~40 endpoints", "No",
        "Blocked", "Sales-led onboarding; API credentials via CSM",
        "https://developer.gladly.com", 2, ""),

    # ---------------- 3. Communications and Messaging ----------------
    R(21, "Slack", "Communications and Messaging", "Team chat platform",
        "OAuth2", "Self-serve", "Full REST", "~200 endpoints", "Yes",
        "Ready", "",
        "https://api.slack.com/authentication", 3, "App-level + user tokens; free workspace works."),
    R(22, "Twilio", "Communications and Messaging", "SMS/voice/WhatsApp CPaaS",
        "Basic", "Self-serve", "Full REST", "~300 endpoints", "Yes",
        "Ready", "",
        "https://www.twilio.com/docs/iam/credentials/api", 3, "Account SID/key as basic auth."),
    R(23, "Zoho Cliq", "Communications and Messaging", "Zoho team chat",
        "OAuth2", "Self-serve", "Narrow REST", "~40 endpoints", "No",
        "Ready with caveats", "Docs are fine but deep features need Zoho bundle",
        "https://www.zoho.com/cliq/help/restapi/api", 2, ""),
    R(24, "Lark", "Communications and Messaging", "Larksuite productivity + chat",
        "Bearer token", "Self-serve", "Full REST", "~400 endpoints", "Yes",
        "Ready", "",
        "https://open.larksuite.com/document/server-docs/getting-started/api-overview", 3,
        "Huge surface; app approval flow is self-serve."),
    R(25, "Pumble", "Communications and Messaging", "Free team chat by CAKE.com",
        "API key", "Self-serve", "Narrow REST", "~25 endpoints", "No",
        "Ready with caveats", "Small API surface; needs paid workspace for API",
        "https://pumble.com/help/integrations/api/pumble-api", 2, ""),
    R(26, "Discord", "Communications and Messaging", "Chat for communities/gamers",
        "Bearer token", "Open", "Full REST", "~100 endpoints", "Yes",
        "Ready", "",
        "https://discord.com/developers/docs/topics/oauth2", 3, "Bot tokens; instant self-serve."),
    R(27, "Telegram", "Communications and Messaging", "Messaging platform",
        "Bearer token", "Open", "Full REST", "~100 methods", "Yes",
        "Ready", "",
        "https://core.telegram.org/bots/api", 3, "Bot API is fully open; MTProto is separate."),
    R(28, "WhatsApp Business", "Communications and Messaging", "WhatsApp business messaging API",
        "OAuth2", "Gated", "Full REST", "~60 endpoints", "Yes",
        "Ready with caveats", "Meta app review + business verification for production",
        "https://developers.facebook.com/docs/whatsapp/cloud-api", 3,
        "Test numbers work immediately; production requires review."),
    R(29, "Aircall", "Communications and Messaging", "Cloud phone system",
        "Basic", "Self-serve", "Narrow REST", "~50 endpoints", "Yes",
        "Ready", "Requires paid account; trial available",
        "https://developer.aircall.io/api-references", 3, ""),
    R(30, "Vonage", "Communications and Messaging", "CPaaS (SMS/voice/video)",
        "Basic", "Self-serve", "Full REST", "~200 endpoints", "Yes",
        "Ready", "",
        "https://developer.vonage.com/en/api", 3, "API key+secret or JWT."),

    # ---------------- 4. Marketing, Ads, Email and Social ----------------
    R(31, "Google Ads", "Marketing, Ads, Email and Social", "Google advertising platform",
        "OAuth2", "Gated", "SDK/CLI only", "gRPC API, ~400 resources", "Yes",
        "Blocked", "Developer-token approval process; basic access is slow to get",
        "https://developers.google.com/google-ads/api/docs/oauth/overview", 3,
        "Test accounts free; production needs approved dev token."),
    R(32, "Meta Ads", "Marketing, Ads, Email and Social", "Facebook/Instagram ads API",
        "OAuth2", "Gated", "Full REST", "~200 endpoints", "Yes",
        "Blocked", "App review + business verification for advanced access",
        "https://developers.facebook.com/docs/marketing-apis", 3,
        "Standard access covers own ads; agent-use needs review."),
    R(33, "LinkedIn Ads", "Marketing, Ads, Email and Social", "LinkedIn advertising API",
        "OAuth2", "Gated", "Full REST", "~80 endpoints", "Yes",
        "Blocked", "Marketing API access requires approved LinkedIn partner application",
        "https://learn.microsoft.com/en-us/linkedin/marketing/", 3, ""),
    R(34, "GoHighLevel", "Marketing, Ads, Email and Social", "Agency marketing platform (white-label)",
        "OAuth2", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "Agency plan required; marketplace app flow",
        "https://highlevel.stoplight.io/docs/integrations", 3, ""),
    R(35, "Mailchimp", "Marketing, Ads, Email and Social", "Email marketing platform",
        "Basic", "Self-serve", "Full REST", "~130 endpoints", "Yes",
        "Ready", "API key on free tier",
        "https://mailchimp.com/developer/marketing/api", 3, ""),
    R(36, "Klaviyo", "Marketing, Ads, Email and Social", "Ecommerce marketing automation",
        "API key", "Self-serve", "Full REST", "~200 endpoints", "Yes",
        "Ready", "",
        "https://developers.klaviyo.com/en/reference/api_overview", 3, ""),
    R(37, "Systeme.io", "Marketing, Ads, Email and Social", "All-in-one funnel builder",
        "API key", "Self-serve", "Narrow REST", "~20 endpoints", "No",
        "Ready with caveats", "Tiny API surface (contacts, tags, campaigns)",
        "https://systeme.io/docs/api", 1,
        "Docs thin; verify endpoint breadth during live pass."),
    R(38, "Pinterest", "Marketing, Ads, Email and Social", "Visual discovery + Pinterest Ads",
        "OAuth2", "Self-serve", "Full REST", "~100 endpoints", "Yes",
        "Ready", "Some scopes need app review",
        "https://developers.pinterest.com/docs/api/v5", 3, ""),
    R(39, "Threads", "Marketing, Ads, Email and Social", "Meta Threads publishing API",
        "OAuth2", "Gated", "Narrow REST", "~15 endpoints", "Yes",
        "Ready with caveats", "App review for production; publishing-only scope",
        "https://developers.facebook.com/docs/threads", 3, ""),
    R(40, "SendGrid", "Marketing, Ads, Email and Social", "Transactional email (Twilio)",
        "Bearer token", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "",
        "https://www.twilio.com/docs/sendgrid/api-reference", 3, ""),

    # ---------------- 5. Ecommerce ----------------
    R(41, "Shopify", "Ecommerce", "Ecommerce storefront platform",
        "OAuth2", "Self-serve", "Full REST", "REST+GraphQL, ~500 endpoints", "Yes",
        "Ready", "Public-app review for distributed apps",
        "https://shopify.dev/docs/api/admin-graphql", 3, "Dev store free; custom apps instant."),
    R(42, "WooCommerce", "Ecommerce", "WordPress ecommerce plugin",
        "HMAC", "Open", "Full REST", "~100 endpoints", "Yes",
        "Ready", "",
        "https://woocommerce.github.io/woocommerce-rest-api-docs", 3,
        "Consumer key/secret with HMAC-SHA1 signature over HTTPS."),
    R(43, "BigCommerce", "Ecommerce", "SaaS ecommerce platform",
        "OAuth2", "Self-serve", "Full REST", "~200 endpoints", "Yes",
        "Ready", "",
        "https://developer.bigcommerce.com/docs/rest-management", 3, ""),
    R(44, "Salesforce Commerce Cloud", "Ecommerce", "Enterprise commerce platform (SFCC)",
        "OAuth2", "Gated", "Full REST", "~150 endpoints", "No",
        "Blocked", "Requires an SFCC instance; no self-serve sandbox",
        "https://developer.salesforce.com/docs/commerce/b2c-commerce/guide/b2c-commercapi.html", 2, ""),
    R(45, "Magento", "Ecommerce", "Open-source ecommerce (Adobe Commerce)",
        "Bearer token", "Open", "Full REST", "~400 endpoints", "No",
        "Ready", "Needs a running store (self-hosted or Adobe)",
        "https://developer.adobe.com/commerce/webapi/rest", 3,
        "Open-source; token via admin or integration."),
    R(46, "Squarespace", "Ecommerce", "Website builder with commerce",
        "OAuth2", "Self-serve", "Narrow REST", "~40 endpoints", "Yes",
        "Ready", "Commerce API needs Business+ plan",
        "https://developers.squarespace.com/commerce-apis", 2, ""),
    R(47, "Ecwid", "Ecommerce", "Embeddable ecommerce storefronts",
        "OAuth2", "Self-serve", "Full REST", "~80 endpoints", "Yes",
        "Ready", "",
        "https://api-docs.ecwid.com", 3, ""),
    R(48, "Gumroad", "Ecommerce", "Sell digital products",
        "Basic", "Open", "Narrow REST", "~20 endpoints", "No",
        "Ready with caveats", "Small API surface, sparse docs",
        "https://gumroad.com/api", 2, ""),
    R(49, "Amazon SP-API", "Ecommerce", "Amazon Selling Partner API",
        "OAuth2", "Gated", "Full REST", "~300 endpoints", "Yes",
        "Blocked", "Developer registration requires professional seller account + vetting",
        "https://developer-docs.amazon.com/sp-api", 3, ""),
    R(50, "Fanbasis", "Ecommerce", "High-ticket creator commerce platform",
        "Bearer token", "Gated", "Narrow REST", "~30 endpoints", "No",
        "Blocked", "Private/invite platform; API access via partnership",
        "https://fanbasis.com", 1,
        "No public API docs found at pass 1; verify during live pass."),
]
