"""Knowledge base, part B: apps 51-100 (Pass-1 priors)."""
from config import AppRecord

R = AppRecord

APPS_B = [
    # ---------------- 6. Data, SEO and Scraping ----------------
    R(51, "DataForSEO", "Data, SEO and Scraping", "SEO data API (SERPs, keywords, backlinks)",
        "Basic", "Self-serve (paid)", "Full REST", "~200 endpoints", "No",
        "Ready", "Pay-as-you-go; live creds after signup",
        "https://docs.dataforseo.com", 3, ""),
    R(52, "SE Ranking", "Data, SEO and Scraping", "SEO platform with public API",
        "API key", "Self-serve (paid)", "Narrow REST", "~30 endpoints", "No",
        "Ready with caveats", "API on Pro+ plans",
        "https://seranking.com/api.html", 2, ""),
    R(53, "Ahrefs", "Data, SEO and Scraping", "SEO backlink/keyword data platform",
        "API key", "Gated", "Narrow REST", "~15 endpoints", "Yes",
        "Ready with caveats", "API v3 needs Enterprise plan or paid API units",
        "https://docs.ahrefs.com/reference/introduction", 2, ""),
    R(54, "MrScraper", "Data, SEO and Scraping", "Web scraping API with parsing",
        "API key", "Self-serve", "Narrow REST", "~15 endpoints", "No",
        "Ready with caveats", "Small API; signup historically approval-based",
        "https://docs.mrscraper.com", 1, ""),
    R(55, "Apify", "Data, SEO and Scraping", "Web scraping/automation actor platform",
        "Bearer token", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "",
        "https://docs.apify.com/api/v2", 3, ""),
    R(56, "Firecrawl", "Data, SEO and Scraping", "LLM-ready web scraping/crawl API",
        "Bearer token", "Self-serve", "Narrow REST", "~25 endpoints", "Yes",
        "Ready", "",
        "https://docs.firecrawl.dev/api-reference/introduction", 3,
        "Vendor ships its own MCP server."),
    R(57, "Bright Data", "Data, SEO and Scraping", "Proxy + web data platform",
        "Bearer token", "Self-serve (paid)", "Full REST", "~100 endpoints", "Yes",
        "Ready", "",
        "https://docs.brightdata.com/api-reference/overview", 3, ""),
    R(58, "Sherlock", "Data, SEO and Scraping", "Find a username across social networks",
        "None", "Open", "None documented", "CLI only", "No",
        "Ready with caveats", "CLI/Python tool, not an API; wrap locally",
        "https://github.com/sherlock-project/sherlock", 3, ""),
    R(59, "Waterfall", "Data, SEO and Scraping", "Waterfall enrichment (contact/company intel)",
        "OAuth2", "Gated", "None documented", "Unknown", "No",
        "Blocked", "Sales-led; no public API docs",
        "https://waterfall.io", 1,
        "Needs outreach to confirm API existence; verify in live pass."),
    R(60, "Clay", "Data, SEO and Scraping", "GTM data-enrichment spreadsheet",
        "Bearer token", "Self-serve (paid)", "Narrow REST", "~60 endpoints", "Yes",
        "Ready", "Credits-based; trial available",
        "https://docs.clay.com", 2, ""),

    # ---------------- 7. Developer, Infra and Data platforms ----------------
    R(61, "GitHub", "Developer, Infra and Data platforms", "Code hosting + collaboration",
        "Bearer token", "Open", "Full REST", "~900 endpoints", "Yes",
        "Ready", "",
        "https://docs.github.com/en/rest", 3, ""),
    R(62, "Vercel", "Developer, Infra and Data platforms", "Frontend cloud / deployments",
        "Bearer token", "Self-serve", "Full REST", "~120 endpoints", "Yes",
        "Ready", "",
        "https://vercel.com/docs/rest-api", 3, ""),
    R(63, "Netlify", "Developer, Infra and Data platforms", "Web hosting / CI for frontends",
        "Bearer token", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "",
        "https://docs.netlify.com/api/get-started", 3, ""),
    R(64, "Cloudflare", "Developer, Infra and Data platforms", "Edge network, DNS, Workers",
        "Bearer token", "Self-serve", "Full REST", "~600 endpoints", "Yes",
        "Ready", "",
        "https://developers.cloudflare.com/api", 3, ""),
    R(65, "Supabase", "Developer, Infra and Data platforms", "Open-source Firebase alternative",
        "API key", "Self-serve", "Full REST", "REST (PostgREST) + Auth + Storage", "Yes",
        "Ready", "",
        "https://supabase.com/docs/reference/api/introduction", 3, ""),
    R(66, "Neo4j", "Developer, Infra and Data platforms", "Graph database",
        "Bearer token", "Open", "Full REST", "HTTP API + Cypher", "Yes",
        "Ready", "Self-host or Aura; local instance needed",
        "https://neo4j.com/docs/http-api/current/actions/result-format", 3, ""),
    R(67, "Snowflake", "Developer, Infra and Data platforms", "Cloud data warehouse",
        "OAuth2", "Self-serve (paid)", "Narrow REST", "SQL REST API + SDKs", "No",
        "Ready with caveats", "SQL-over-REST only; SDKs do the heavy lifting",
        "https://docs.snowflake.com/en/developer-guide/sql-api/intro", 2, ""),
    R(68, "MongoDB Atlas", "Developer, Infra and Data platforms", "Cloud MongoDB service",
        "Bearer token", "Self-serve", "Full REST", "Admin API ~200 endpoints", "Yes",
        "Ready", "",
        "https://www.mongodb.com/docs/atlas/reference/api/", 3, ""),
    R(69, "Datadog", "Developer, Infra and Data platforms", "Observability platform",
        "API key", "Self-serve", "Full REST", "~500 endpoints", "Yes",
        "Ready", "Dual keys: API key + Application key",
        "https://docs.datadoghq.com/api/latest/", 3, ""),
    R(70, "Sentry", "Developer, Infra and Data platforms", "Error monitoring",
        "Bearer token", "Self-serve", "Full REST", "~100 endpoints", "Yes",
        "Ready", "",
        "https://docs.sentry.io/api", 3, ""),

    # ---------------- 8. Productivity and Project Management ----------------
    R(71, "Notion", "Productivity and Project Management", "Docs + databases workspace",
        "OAuth2", "Self-serve", "Full REST", "~60 endpoints", "Yes",
        "Ready", "Internal integrations instant",
        "https://developers.notion.com/reference/intro", 3, ""),
    R(72, "Airtable", "Productivity and Project Management", "Spreadsheet-database hybrid",
        "Bearer token", "Self-serve", "Full REST", "~50 endpoints", "Yes",
        "Ready", "",
        "https://airtable.com/developers/web/api/introduction", 3, ""),
    R(73, "Linear", "Productivity and Project Management", "Issue tracking for product teams",
        "API key", "Self-serve", "GraphQL", "GraphQL schema, ~100 ops", "Yes",
        "Ready", "",
        "https://developers.linear.app", 3, "Personal API keys + OAuth."),
    R(74, "Jira", "Productivity and Project Management", "Issue tracking (Atlassian)",
        "Basic", "Self-serve", "Full REST", "~300 endpoints", "Yes",
        "Ready", "Free cloud tier; API token in account settings",
        "https://developer.atlassian.com/cloud/jira/platform/rest/v3", 3, ""),
    R(75, "Asana", "Productivity and Project Management", "Work management",
        "Bearer token", "Self-serve", "Full REST", "~150 endpoints", "Yes",
        "Ready", "Free tier works",
        "https://developers.asana.com/reference", 3, ""),
    R(76, "Monday.com", "Productivity and Project Management", "Work OS",
        "Bearer token", "Self-serve", "GraphQL", "GraphQL API v2", "Yes",
        "Ready", "14-day trial; API v2 on all tiers",
        "https://developer.monday.com/api-reference", 3, ""),
    R(77, "ClickUp", "Productivity and Project Management", "All-in-one productivity app",
        "Bearer token", "Self-serve", "Full REST", "~120 endpoints", "Yes",
        "Ready", "",
        "https://clickup.com/api/developer-portal", 3, ""),
    R(78, "Coda", "Productivity and Project Management", "Docs with app-like building blocks",
        "Bearer token", "Self-serve", "Full REST", "~40 endpoints", "Yes",
        "Ready", "",
        "https://coda.io/developers/apis/v1", 3, ""),
    R(79, "Smartsheet", "Productivity and Project Management", "Enterprise work management",
        "Bearer token", "Self-serve", "Full REST", "~100 endpoints", "Yes",
        "Ready", "Trial available; API on all plans",
        "https://smartsheet.redoc.ly", 3, ""),
    R(80, "Harvest", "Productivity and Project Management", "Time tracking + invoicing",
        "Bearer token", "Self-serve", "Full REST", "~40 endpoints", "Yes",
        "Ready", "Free single-user tier; developer token program",
        "https://help.getharvest.com/api-v2", 3, ""),

    # ---------------- 9. Finance and Fintech ----------------
    R(81, "Stripe", "Finance and Fintech", "Payments platform",
        "Bearer token", "Self-serve", "Full REST", "~400 endpoints", "Yes",
        "Ready", "",
        "https://docs.stripe.com/api", 3, "Test mode instant; keys in dashboard."),
    R(82, "Plaid", "Finance and Fintech", "Bank-account connectivity API",
        "Bearer token", "Gated", "Full REST", "~200 endpoints", "Yes",
        "Ready with caveats", "Sandbox instant; production needs company verification",
        "https://plaid.com/docs/api/", 3, ""),
    R(83, "Binance", "Finance and Fintech", "Crypto exchange",
        "HMAC", "Self-serve", "Full REST", "~120 endpoints", "No",
        "Ready", "API keys instant; HMAC-SHA256 signing",
        "https://developers.binance.com/docs/binance-spot-api-docs/rest-api", 3, ""),
    R(84, "Paygent Connect", "Finance and Fintech", "Payment ops (NMI-powered gateway)",
        "API key", "Gated", "Narrow REST", "~30 endpoints", "No",
        "Blocked", "NMI partner onboarding; no public self-serve signup",
        "https://paygent.io", 1,
        "Very obscure; verify docs existence in live pass."),
    R(85, "iPayX", "Finance and Fintech", "Payment infrastructure startup",
        "Bearer token", "Gated", "None documented", "Unknown", "No",
        "Blocked", "No public API docs; contact-sales only",
        "https://ipayx.ai", 1, "Verify in live pass."),
    R(86, "QuickBooks", "Finance and Fintech", "SMB accounting (Intuit)",
        "OAuth2", "Self-serve", "Full REST", "~100 endpoints", "No",
        "Ready", "Sandbox company instant; production needs Intuit app review",
        "https://developer.intuit.com/app/developer/qbo/docs/api", 3, ""),
    R(87, "Xero", "Finance and Fintech", "Small-business accounting",
        "OAuth2", "Self-serve", "Full REST", "~100 endpoints", "No",
        "Ready", "Partner-app approval for production",
        "https://developer.xero.com/documentation", 3, ""),
    R(88, "Brex", "Finance and Fintech", "Spend management / corporate cards",
        "OAuth2", "Gated", "GraphQL", "GraphQL API", "No",
        "Ready with caveats", "Customer token needs Brex dashboard admin",
        "https://developer.brex.com", 2, ""),
    R(89, "Ramp", "Finance and Fintech", "Corporate cards + spend management",
        "OAuth2", "Gated", "Full REST", "~80 endpoints", "No",
        "Ready with caveats", "Account admin must create client; business verification",
        "https://docs.ramp.com", 2, ""),
    R(90, "PitchBook", "Finance and Fintech", "PE/VC market-intelligence database",
        "None", "Gated", "None documented", "Unknown", "No",
        "Blocked", "Subscription research product; API is partner-gated",
        "https://pitchbook.com", 2, ""),

    # ---------------- 10. AI, Research and Media-native ----------------
    R(91, "NotebookLM", "AI, Research and Media-native", "Notebook + source-grounded AI (Google)",
        "OAuth2", "Gated", "None documented", "Unknown", "No",
        "Blocked", "No public API; enterprise-only via Gemini/Vertex waitlist",
        "https://cloud.google.com/gemini", 2, ""),
    R(92, "Otter AI", "AI, Research and Media-native", "AI meeting notes/transcripts",
        "OAuth2", "Gated", "Narrow REST", "MCP server + minimal REST", "Yes",
        "Ready with caveats", "MCP server exists but OAuth apps are waitlisted",
        "https://help.otter.ai", 1, "MCP claim needs live confirmation."),
    R(93, "Fathom", "AI, Research and Media-native", "AI meeting assistant",
        "OAuth2", "Gated", "Narrow REST", "~30 endpoints", "No",
        "Ready with caveats", "Public API exists but requires approval/minimum seats",
        "https://fathom.video", 1, "Confirm API docs URL in live pass."),
    R(94, "Consensus", "AI, Research and Media-native", "AI research/paper search engine",
        "OAuth2", "Gated", "Narrow REST", "~10 endpoints", "No",
        "Ready with caveats", "OAuth access 'requested' - partnership conversations",
        "https://consensus.app/home/dapid/", 1, "Confirm OAuth status in live pass."),
    R(95, "Reducto", "AI, Research and Media-native", "Document parsing API for LLMs",
        "Bearer token", "Self-serve", "Full REST", "~40 endpoints", "Yes",
        "Ready", "",
        "https://docs.reducto.ai", 2, ""),
    R(96, "Devin", "AI, Research and Media-native", "AI software engineer (Cognition)",
        "Bearer token", "Self-serve (paid)", "Narrow REST", "~20 endpoints", "Yes",
        "Ready", "ACU-based pricing; API key from dashboard",
        "https://docs.devin.ai", 2, ""),
    R(97, "Higgsfield", "AI, Research and Media-native", "AI video/content generation suite",
        "Bearer token", "Self-serve (paid)", "Narrow REST", "CLI + ~15 endpoints", "No",
        "Ready with caveats", "CLI-first; API docs sparse",
        "https://higgsfield.ai", 1, "Confirm CLI/API split in live pass."),
    R(98, "Mermaid CLI", "AI, Research and Media-native", "Render Mermaid diagrams to SVG/PNG",
        "None", "Open", "None documented", "CLI only", "No",
        "Ready with caveats", "Local CLI, not an API; wrap via subprocess",
        "https://github.com/mermaid-js/mermaid-cli", 3, ""),
    R(99, "YouTube Transcript", "AI, Research and Media-native", "Fetch YouTube transcripts",
        "API key", "Self-serve", "Narrow REST", "~5 endpoints", "Yes",
        "Ready", "",
        "https://transcriptapi.com", 1, "Third-party API; verify docs live in live pass."),
    R(100, "Grain", "AI, Research and Media-native", "Meeting recording + notes",
        "Bearer token", "Gated", "Narrow REST", "~40 endpoints", "No",
        "Ready with caveats", "API access historically partner-gated",
        "https://grain.com", 1, "Check current API access policy in live pass."),
]
